### ISSUE TITLE
Avrae Snippets Damage type

### ISSUE THREAD

**Issue by nmartucci** [avrae/avrae-docs#14]
Less of an issue more of a question, is there a way to set damage type when adding an additional dice to the damage roll? For instance, the Druid circle of spores has a feature called Symbiotic entity where upon a melee attack, it does 1d6 of poison. however using the snippets i can only get the d6 roll but it reflects the same damage type of the primary damage roll. 

Is there a way to alter this?

**Comment by Croebh** [comment]
Hey,

`-d "1d6[poison]"`

Should do the trick. I imagine you tried something similar to this, but had
a space between the `1d6` and `[poison]`, without quotes.

PS - The best way to get assistance with the bot is on the discord server!
https://discord.gg/bE5zTQx
There are plenty of users that are more than willing to assist, on top of
just being a good community with great conversations!

Have a nice day!

**Comment by nmartucci** [comment]
Thanks a bunch, Noted!
